In [1]:
import numpy

# one dimensional array

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

# two dimentional array

In [5]:
n1 = n.reshape(3,9)

In [9]:
n1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

# three dimentional array

In [7]:
n2 = n.reshape(3,3,3)

In [8]:
n2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

C:\Users\Rom\AppData\Local\Temp/ipykernel_9828/2508824919.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = numpy.asarray([[123,12,123,12,33],[],[]])


In [12]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [14]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


# Convert Images to Numpy Arrays

In [15]:
import cv2

In [19]:
imageGray = cv2.imread("smallgray.png", 0)

In [20]:
imageGray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
cv2.imwrite("newsmallgray.png", imageGray)

True

# Indexing, Slicing, and Iterating Numpy Arrays

In [22]:
imageGray.shape

(3, 5)

In [23]:
imageGray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
imageGray[0:2, 1:3]

array([[158, 104],
       [125, 255]], dtype=uint8)

In [28]:
imageGray[2, :]

array([209, 134, 255,  97, 182], dtype=uint8)

In [30]:
imageGray[:, 3]

array([121, 255,  97], dtype=uint8)

In [31]:
imageGray[2, 3]

97

In [32]:
for i in imageGray:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [34]:
for i in imageGray.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [35]:
for i in imageGray.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


# Stacking and Splitting Numpy Arrays

In [36]:
imageGray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [37]:
imageH = numpy.hstack((imageGray,imageGray))

In [38]:
imageH

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [39]:
imageH = numpy.hstack((imageGray,imageGray,imageGray))

In [40]:
print(image)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [41]:
imageV = numpy.vstack((imageGray,imageGray,imageGray))

In [43]:
imageV

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
splitLstH = numpy.hsplit(imageV, 5)

In [49]:
splitLstH

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [52]:
splitLstV = numpy.vsplit(imageV, 3)

In [53]:
splitLstV

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [54]:
type(splitLstV)

list

In [56]:
splitLstV[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)